
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run unit tests
      run: ./gradlew -p plugins/compiler-plugin clean test --info -PintellijPublishToken=stub
